export const matchList = [
    { regex: /(?:Washington)(?:.*United States)/i, stamp: "Washington" },
    { regex: /(?:Tokyo)(?:.*Japan)/i, stamp: "Tokyo" },
    { regex: /(?:Seoul)(?:.*Korea)/i, stamp: "Seoul" },
    { regex: /(?:Vancouver)(?:.*Canada)/i, stamp: "Vancouver" },
    { regex: /(?:Moscow)(?:.*Russia)/i, stamp: "Moscow" },
    { regex: /(?:Paris)(?:.*France)/i, stamp: "Paris" },
    { regex: /(?:Cape)(?:.*South Africa)/i, stamp: "Cape_Town" },
    { regex: /(?:Rome)(?:.*Italy)/i, stamp: "Rome" },
    { regex: /(?:Oaxaca)(?:.*Mexico)/i, stamp: "Oaxaca" },
    { regex: /(?:Cappadocia)(?:.*Turkey)/i, stamp: "Cappadocia" },
    { regex: /(?:Chefchaouen)(?:.*Morocco)/i, stamp: "Chefchaouen" },
    { regex: /(?:Amsterdam)(?:.*Netherlands)/i, stamp: "Amsterdam" },
    { regex: /(?:Barcelona)(?:.*Spain)/i, stamp: "Barcelona" },
    { regex: /(?:Beijing)(?:.*China)/i, stamp: "Beijing" },
    { regex: /(?:Cairo)(?:.*Egypt)/i, stamp: "Cairo" },
    { regex: /(?:Cartagena)(?:.*Colombia)/i, stamp: "Cartagena" },
    { regex: /(?:(E|É)vora)(?:.*Portugal)/i, stamp: "Evora" },
    { regex: /(?:Hawaii)(?:.*United States)/i, stamp: "Hawaii" },
    { regex: /(?:Jerusalem)(?:.*Israel)/i, stamp: "Jerusalem" },
    { regex: /(?:London)(?:.*England)/i, stamp: "London" },
    { regex: /(?:Los Angeles)(?:.*United States)/i, stamp: "Los_Angeles" },
    { regex: /(?:Naples)(?:.*Italy)/i, stamp: "Naples" },
    { regex: /(?:New York)(?:.*United States)/i, stamp: "New_York" },
    { regex: /(?:Paris)(?:.*France)/i, stamp: "Paris" },
    { regex: /(?:Port Louis)(?:.*Mauritius)/i, stamp: "Port_Louis" },
    { regex: /(?:Singapore)/i, stamp: "Singapore" },
    { regex: /(?:Oia)(?:.*Greece)/i, stamp: "Santorini" },
    { regex: /(?:Sydney)(?:.*Australia)/i, stamp: "Sydney" },
    { regex: /(?:Nuuk)(?:.*Greenland)/i, stamp: "Nuuk" },
    { regex: /(?:Bordeaux)(?:.*France)/i, stamp: "Bordeaux" },
    { regex: /(?:Christchurch)(?:.*New Zealand)/i, stamp: "Christchurch" },
    { regex: /(?:Havana)(?:.*Cuba)/i, stamp: "Havana" },
    { regex: /(?:Istanbul)(?:.*(Turkey|Türkiye))/i, stamp: "Istanbul" },
    { regex: /(?:Hamburg)(?:.*Germany)/i, stamp: "Hamburg" },
    { regex: /(?:Hong Kong)/i, stamp: "Hong_Kong" },
    { regex: /(?:Lisbon)(?:.*Portugal)/i, stamp: "Lisbon" },
    { regex: /(?:Maputo)(?:.*Mozambique)/i, stamp: "Maputo" },
    { regex: /(?:Antarctica)/i, stamp: "Antarctica" },
  ];