export const totalStamps = [
    { city: "Amsterdam", country: "Netherlands" },
    { city: "Antarctica", country: "Antarctica" },
    { city: "Barcelona", country: "Spain" },
    { city: "Beijing", country: "China" },
    { city: "Bordeaux", country: "Paris" },
    { city: "Cairo", country: "Egypt" },
    { city: "Cape Town", country: "South Africa" },
    { city: "Cappadocia", country: "Turkey" },
    { city: "Cartagena", country: "Colombia" },
    { city: "Chefchaouen", country: "Morocco" },
    { city: "Christchurch", country: "New Zealand" },
    { city: "Evora", country: "Portugal" },
    { city: "Hamburg", country: "Germany" },
    { city: "Havana", country: "Cuba" },
    { city: "Hawaii", country: "United States" },
    { city: "Hong Kong", country: "China" },
    { city: "Istanbul", country: "Turkey" },
    { city: "Jerusalem", country: "Israel" },
    { city: "Lisbon", country: "Portugal" },
    { city: "London", country: "England" },
    { city: "Los Angeles", country: "United States" },
    { city: "Maputo", country: "Mozambique" },
    { city: "Moscow", country: "Russia" },
    { city: "Naples", country: "Italy" },
    { city: "New York", country: "United States" },
    { city: "Nuuk", country: "Greenland" },
    { city: "Oaxaca", country: "Mexico" },
    { city: "Paris", country: "France" },
    { city: "Port Louis", country: "Mauritius" },
    { city: "Rome", country: "Italy" },
    { city: "Santorini", country: "Greece" },
    { city: "Seoul", country: "South Korea" },
    { city: "Singapore", country: "Singapore" },
    { city: "Sydney", country: "Australia" },
    { city: "Tokyo", country: "Japan" },
    { city: "Vancouver", country: "Canada" },
    { city: "Washington", country: "United States" },
  ];